// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgV5o0KXeyhwWD3OT0kaow0k9R7q3AxeY',
    appId: '1:485091687272:web:b0317dacd3a20d3b24f4dd',
    messagingSenderId: '485091687272',
    projectId: 'furnix-store-1fcd6',
    authDomain: 'furnix-store-1fcd6.firebaseapp.com',
    storageBucket: 'furnix-store-1fcd6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbOXUaFWrKOPNiu2oDGuWJPX4nML-FjKw',
    appId: '1:485091687272:android:7a782b07bfbe291024f4dd',
    messagingSenderId: '485091687272',
    projectId: 'furnix-store-1fcd6',
    storageBucket: 'furnix-store-1fcd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ga3W631DmFSixnn7ePb_r6e7nuLadCs',
    appId: '1:485091687272:ios:bdf4bd8c99f39b0f24f4dd',
    messagingSenderId: '485091687272',
    projectId: 'furnix-store-1fcd6',
    storageBucket: 'furnix-store-1fcd6.appspot.com',
    iosBundleId: 'com.example.furnixStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ga3W631DmFSixnn7ePb_r6e7nuLadCs',
    appId: '1:485091687272:ios:bdf4bd8c99f39b0f24f4dd',
    messagingSenderId: '485091687272',
    projectId: 'furnix-store-1fcd6',
    storageBucket: 'furnix-store-1fcd6.appspot.com',
    iosBundleId: 'com.example.furnixStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgV5o0KXeyhwWD3OT0kaow0k9R7q3AxeY',
    appId: '1:485091687272:web:b73d91a258f4cff124f4dd',
    messagingSenderId: '485091687272',
    projectId: 'furnix-store-1fcd6',
    authDomain: 'furnix-store-1fcd6.firebaseapp.com',
    storageBucket: 'furnix-store-1fcd6.appspot.com',
  );
}
